import sqlite3


def _format_minutes(total_minutes: int) -> str:
    """Format minutes since midnight as HH:MM."""
    hours, minutes = divmod(total_minutes, 60)
    return f"{hours:02d}:{minutes:02d}"


def _generate_windows(prod: str, shelf_time: int) -> list[tuple[str, str, str, str]]:
    """
    Generate product-specific public-hours windows from 11:00 to 23:59.

    Each row is: (prod, time_window, start_hour, end_hour). The start/end values are
    stored as HH:MM strings so SQLite can compare them directly with ItemOrders.hour.
    """
    if shelf_time <= 0:
        raise ValueError(
            f"Invalid shelf_time for product '{prod}': expected a positive integer, got {shelf_time}."
        )

    opening_minutes = 11 * 60
    closing_minutes = 23 * 60 + 59
    windows: list[tuple[str, str, str, str]] = []

    start = opening_minutes
    while start <= closing_minutes:
        end = min(start + shelf_time - 1, closing_minutes)
        start_hour = _format_minutes(start)
        end_hour = _format_minutes(end)
        windows.append((prod, f"{start_hour}_{end_hour}", start_hour, end_hour))
        start += shelf_time

    return windows


def _get_generated_window_rows(
    conn: sqlite3.Connection, target_name: str
) -> list[tuple[str, str, str, str]]:
    """Read Items.shelf_time dynamically and generate all product-specific time windows."""
    item_rows = conn.execute(
        """
        SELECT name, shelf_time
        FROM Items
        ORDER BY name;
        """
    ).fetchall()

    if not item_rows:
        raise ValueError(
            f"Cannot update {target_name}: Items table is empty. "
            "Insert production items before running this update."
        )

    window_rows: list[tuple[str, str, str, str]] = []
    for prod, shelf_time in item_rows:
        window_rows.extend(_generate_windows(str(prod), int(shelf_time)))

    return window_rows


def update_event_weather_insight_table(db_path: str) -> None:
    """
    Fully recalculate EventWeatherInsight from historical ItemOrders + Calendar data.

    The table is cleared and rebuilt every time this function runs. Demand multipliers are
    calculated per product-specific time window using each product's shelf_time from Items.
    """
    try:
        with sqlite3.connect(db_path) as conn:
            conn.execute("PRAGMA foreign_keys = ON;")

            try:
                # Step 1: Read shelf_time dynamically from Items. Product names are not hardcoded.
                window_rows = _get_generated_window_rows(conn, "EventWeatherInsight")

                # Wrap the destructive refresh and insert batch in one transaction.
                conn.execute("BEGIN;")

                # Temporary window mapping generated by Python and consumed by SQL CTEs.
                conn.execute("DROP TABLE IF EXISTS temp_event_weather_windows;")
                conn.execute(
                    """
                    CREATE TEMP TABLE temp_event_weather_windows (
                        prod TEXT NOT NULL,
                        time_window TEXT NOT NULL,
                        start_hour TEXT NOT NULL,
                        end_hour TEXT NOT NULL,
                        PRIMARY KEY (prod, time_window)
                    );
                    """
                )
                conn.executemany(
                    """
                    INSERT INTO temp_event_weather_windows
                        (prod, time_window, start_hour, end_hour)
                    VALUES (?, ?, ?, ?);
                    """,
                    window_rows,
                )

                # Step 4: Fully replace EventWeatherInsight every time this function is called.
                conn.execute("DELETE FROM EventWeatherInsight;")

                # Steps 2 and 3: Heavy aggregation is performed in SQL with CTEs.
                #
                # daily_totals intentionally starts from Calendar x generated windows and LEFT JOINs
                # ItemOrders. This preserves zero-demand days/windows, allowing global_mean == 0 to
                # be handled explicitly by the pct_dif safety rules.
                conn.execute(
                    """
                    WITH daily_totals AS (
                        SELECT
                            w.time_window,
                            w.prod,
                            c.date,
                            UPPER(c.weather) AS weather,
                            UPPER(c.event) AS event,
                            COALESCE(SUM(io.item_quantity), 0) AS daily_total
                        FROM temp_event_weather_windows w
                        CROSS JOIN Calendar c
                        LEFT JOIN ItemOrders io
                            ON io.date = c.date
                           AND io.item = w.prod
                           AND substr(io.hour, 1, 5) BETWEEN w.start_hour AND w.end_hour
                        GROUP BY
                            w.time_window,
                            w.prod,
                            c.date,
                            UPPER(c.weather),
                            UPPER(c.event)
                    ),
                    means AS (
                        SELECT
                            time_window,
                            prod,
                            AVG(daily_total) AS global_mean,
                            AVG(CASE WHEN weather = 'RAINING' THEN daily_total END) AS mean_raining,
                            AVG(CASE WHEN weather = 'NOT_RAINING' THEN daily_total END) AS mean_not_raining,
                            AVG(CASE WHEN event = 'NONE' THEN daily_total END) AS mean_event_none,
                            AVG(CASE WHEN event = 'HOLIDAY' THEN daily_total END) AS mean_event_holiday,
                            AVG(CASE WHEN event = 'SMALL_EVENT' THEN daily_total END) AS mean_event_small,
                            AVG(CASE WHEN event = 'BIG_EVENT' THEN daily_total END) AS mean_event_big
                        FROM daily_totals
                        GROUP BY time_window, prod
                    )
                    INSERT INTO EventWeatherInsight (
                        time_window,
                        prod,
                        pct_dif_raining,
                        pct_dif_not_raining,
                        pct_dif_event_none,
                        pct_dif_event_holiday,
                        pct_dif_event_small,
                        pct_dif_event_big
                    )
                    SELECT
                        time_window,
                        prod,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_raining, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_raining, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_raining,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_not_raining, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_not_raining, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_not_raining,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_event_none, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_event_none, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_event_none,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_event_holiday, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_event_holiday, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_event_holiday,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_event_small, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_event_small, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_event_small,
                        CASE
                            WHEN global_mean IS NULL OR global_mean = 0 THEN 1.0
                            WHEN COALESCE(mean_event_big, 0) / global_mean = 0 THEN 1.0
                            ELSE MAX(MIN(COALESCE(mean_event_big, 0) / global_mean, 5.0), 0.5)
                        END AS pct_dif_event_big
                    FROM means;
                    """
                )

                conn.execute("DROP TABLE IF EXISTS temp_event_weather_windows;")
                conn.commit()

            except Exception:
                conn.rollback()
                raise

    except sqlite3.Error as exc:
        raise RuntimeError(
            f"Failed to update EventWeatherInsight for database '{db_path}': {exc}"
        ) from exc


def update_day_prediction_table(db_path: str) -> None:
    """
    Fully recalculate DayPrediction from historical ItemOrders + Calendar data.

    For each lowercase weekday, production item, and product-specific time window, this stores
    CEIL(VALUEs), where VALUEs is an adaptive weighted moving average over up to the 8 most
    recent occurrences of that weekday.
    """
    try:
        with sqlite3.connect(db_path) as conn:
            conn.execute("PRAGMA foreign_keys = ON;")

            try:
                # Step 1: Generate product-specific time windows from Items.shelf_time.
                # Product names and window sizes are read dynamically from the database.
                window_rows = _get_generated_window_rows(conn, "DayPrediction")

                # Step 4: Wrap the destructive refresh and new insert batch in one transaction.
                conn.execute("BEGIN;")

                # Temporary window mapping generated by Python and consumed by SQL CTEs.
                conn.execute("DROP TABLE IF EXISTS temp_day_prediction_windows;")
                conn.execute(
                    """
                    CREATE TEMP TABLE temp_day_prediction_windows (
                        prod TEXT NOT NULL,
                        time_window TEXT NOT NULL,
                        start_hour TEXT NOT NULL,
                        end_hour TEXT NOT NULL,
                        PRIMARY KEY (prod, time_window)
                    );
                    """
                )
                conn.executemany(
                    """
                    INSERT INTO temp_day_prediction_windows
                        (prod, time_window, start_hour, end_hour)
                    VALUES (?, ?, ?, ?);
                    """,
                    window_rows,
                )

                # Step 4: Fully replace DayPrediction every time this function is called.
                conn.execute("DELETE FROM DayPrediction;")

                # Steps 2, 3, and 4: Aggregate historical demand, rank up to 8 previous weekday
                # occurrences, apply adaptive recency weights, then insert CEIL(VALUEs).
                #
                # daily_totals starts from Calendar x generated windows and LEFT JOINs ItemOrders.
                # This treats days/windows with no orders as zero-demand historical occurrences,
                # which is important for an accurate weekday moving average.
                conn.execute(
                    """
                    WITH daily_totals AS (
                        SELECT
                            c.date,
                            CASE
                                WHEN c.date LIKE '__/__/____'
                                    THEN substr(c.date, 7, 4) || '-' || substr(c.date, 4, 2) || '-' || substr(c.date, 1, 2)
                                ELSE c.date
                            END AS sortable_date,
                            LOWER(c.week_day) AS week_day,
                            w.time_window,
                            w.prod,
                            COALESCE(SUM(io.item_quantity), 0) AS daily_total
                        FROM temp_day_prediction_windows w
                        CROSS JOIN Calendar c
                        LEFT JOIN ItemOrders io
                            ON io.date = c.date
                           AND io.item = w.prod
                           AND substr(io.hour, 1, 5) BETWEEN w.start_hour AND w.end_hour
                        GROUP BY
                            c.date,
                            sortable_date,
                            LOWER(c.week_day),
                            w.time_window,
                            w.prod
                    ),
                    ranked_days AS (
                        SELECT
                            date,
                            sortable_date,
                            week_day,
                            time_window,
                            prod,
                            daily_total,
                            ROW_NUMBER() OVER (
                                PARTITION BY week_day, prod, time_window
                                ORDER BY sortable_date DESC
                            ) AS row_num,
                            COUNT(*) OVER (
                                PARTITION BY week_day, prod, time_window
                            ) AS available_days
                        FROM daily_totals
                    ),
                    weighted_days AS (
                        SELECT
                            week_day,
                            time_window,
                            prod,
                            daily_total,
                            CASE
                                WHEN available_days >= 8 THEN 9 - row_num
                                ELSE available_days + 1 - row_num
                            END AS weight
                        FROM ranked_days
                        WHERE row_num <= 8
                    ),
                    predictions AS (
                        SELECT
                            week_day,
                            time_window,
                            prod,
                            SUM(daily_total * weight) * 1.0 / NULLIF(SUM(weight), 0) AS values_avg
                        FROM weighted_days
                        GROUP BY week_day, time_window, prod
                    )
                    INSERT INTO DayPrediction (
                        week_day,
                        time_window,
                        prod,
                        prediction
                    )
                    SELECT
                        week_day,
                        time_window,
                        prod,
                        values_avg AS prediction
                    FROM predictions;
                    """
                )

                conn.execute("DROP TABLE IF EXISTS temp_day_prediction_windows;")
                conn.commit()

            except Exception:
                conn.rollback()
                raise

    except sqlite3.Error as exc:
        raise RuntimeError(
            f"Failed to update DayPrediction for database '{db_path}': {exc}"
        ) from exc
