/*
    Database schema for sales ingestion, predictive demand inputs, production parameters,
    real-time simulation multipliers, and end-of-day KPI persistence.

    Important runtime notes from the implementation guide:
    - Time windows are product-dependent and must be generated by the backend using Items.shelf_time.
      Examples: fries may use 10-minute windows, burgers 20-minute windows, apple pie 30/40-minute windows.
    - ItemOrders is a view that replaces Sales as the predictive-model input. CALCULO()/forecast logic
      should query ItemOrders, not raw Sales.
    - Always protect divisions with NULLIF(denominator, 0). Use COALESCE(..., 1.0) for missing ratios so
      predictive formulas keep working in low-traffic or unseen event/weather windows.
    - OrdersInsight should not be truncated daily if historical runs/backtesting are needed. Prefer filtering
      by date-encoded time_window values, or add a sim_date column later for multi-day backtesting.
*/

BEGIN TRANSACTION;

/*
    1. RAW SALES DATA (Direct CSV Import)

    Stores the imported CSV lines exactly at invoice-line granularity.
    Primary key is (invoice_id, line_nr), because one invoice can contain multiple menu lines.
*/
CREATE TABLE IF NOT EXISTS Sales (
    date DATE NOT NULL,
    hour TIME NOT NULL,
    invoice_id INT NOT NULL,
    invoice_nr VARCHAR(20) NOT NULL,
    line_nr INT NOT NULL,
    parent_id INT,
    product_id INT,
    product_name VARCHAR(50),
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (invoice_id, line_nr)
);

/*
    2. CALENDAR CONTEXT

    Provides day-level context used by predictive aggregation.
    Event/weather labels are intentionally simple categorical values expected by EventWeatherInsight:
    - weather examples: 'raining', 'not_raining'
    - event examples: 'none', 'holiday', 'small', 'big'
*/
CREATE TABLE IF NOT EXISTS Calendar (
    date DATE PRIMARY KEY,
    week_day VARCHAR(10),
    event VARCHAR(20),
    weather VARCHAR(20)
);

/*
    3. MENU & PRODUCTION MAPPING

    Maps menu products sold in Sales to bottleneck production items.
    Only rows with a non-empty item and item_quantity > 0 appear in the ItemOrders view.

    Examples:
    - product_name = 'Menu Double Burger', item = 'pork_burger', item_quantity = 1
    - product_name = 'Fries Large', item = 'fries', item_quantity = 1

    The multiplication Sales.quantity * Menu.item_quantity handles bulk orders and menu bundles.
*/
CREATE TABLE IF NOT EXISTS Menu (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    base_price DECIMAL(10,2),
    item VARCHAR(30),
    item_quantity INT
);

/*
    4. PARSED ITEM ORDERS VIEW (Predictive Model Input)

    Derived directly from Sales + Menu and used by forecasting/CALCULO() logic instead of Sales.
    This is a view, not a physical table, because the fields are fully derived from existing tables.
    No trigger is needed: newly inserted Sales rows become visible here automatically as long as the
    corresponding Menu mapping already exists.

    Important annotations:
    - Only mapped bottleneck production items appear here, for example fries, beef_burger, etc.
    - item_quantity is the exact derived quantity for that invoice/product line.
    - Sales.quantity * Menu.item_quantity preserves exact derived quantities for bulk orders and bundles.
*/
CREATE VIEW IF NOT EXISTS ItemOrders AS
SELECT
    s.date,
    s.hour,
    s.invoice_id,
    m.item,
    s.quantity * m.item_quantity AS item_quantity
FROM Sales s
INNER JOIN Menu m ON s.product_id = m.product_id
WHERE m.item IS NOT NULL
  AND TRIM(m.item) != ''
  AND m.item_quantity > 0;

/*
    5. PRODUCTION PARAMETERS (Spec Sec 1.6)

    Stores the physical/simulation parameters per bottleneck production item.
    - production_time: minutes required to produce a batch/item.
    - shelf_time: minutes before an item expires and moves SHELF -> TRASH.
    - max_capacity: maximum simultaneous production/shelf capacity used by the simulator.
*/
CREATE TABLE IF NOT EXISTS Items (
    name VARCHAR(30) PRIMARY KEY,
    production_time INT NOT NULL,
    shelf_time INT NOT NULL,
    max_capacity INT NOT NULL
);

/*
    6. REAL-TIME MULTIPLIER TRACKING (Spec Sec 6)

    Runtime accumulator for MULTIPLICADOR_PROPRIO_DIA.

    Upsert routine called at the end of every product-specific time_window during simulation:
    -- ✅ Corrected runtime upsert:
        INSERT INTO OrdersInsight (date, time_window, prod, nr_predicted_orders, nr_real_orders)
        VALUES (?, ?, ?, ?, ?)
        ON CONFLICT (date, time_window, prod)
        DO UPDATE SET
            nr_predicted_orders = EXCLUDED.nr_predicted_orders,
            nr_real_orders = EXCLUDED.nr_real_orders;

    Annotations:
    - nr_real_orders increments when tempo_atual == order.HORA_EMISSAO
      and the order activates to ESPERA.
    - nr_predicted_orders increments only when HORA_EMISSAO == HORA_RECEBIDO,
      meaning the order was fulfilled instantly from SHELF.
    - Backend multiplier formula:
          MULTIPLICADOR_PROPRIO_DIA = nr_real_orders / NULLIF(nr_predicted_orders, 0)
      Default to 1.0 when the division yields NULL.
*/
CREATE TABLE IF NOT EXISTS OrdersInsight (
    date DATE NOT NULL,
    time_window VARCHAR(15) NOT NULL,
    prod VARCHAR(30) NOT NULL,
    nr_predicted_orders INT DEFAULT 0,
    nr_real_orders INT DEFAULT 0,
    PRIMARY KEY (date, time_window, prod)
);

/*
    7. PRE-CALCULATED EVENT/WEATHER IMPACT (Spec Sec 2.7)

    Stores PCT_DIFERENCIAÇÃO ratios comparing conditional demand to historical baseline demand.

    Formula:
        pct_dif = Avg Orders in Condition / Avg Orders Baseline

    Interpretation:
    - Values > 1.0 mean demand increases under that condition.
    - Values < 1.0 mean demand decreases under that condition.
    - Use COALESCE(..., 1.0) when a condition is missing.

    Time-window annotation:
    - time_window must be generated dynamically by the backend using Items.shelf_time before aggregation.
    - If you materialize a temporary/source dataset for nightly refresh, include columns:
          time_window, item/prod, item_quantity, date

    Nightly refresh outline:
    - Calculate baseline average demand per time_window + prod across all conditions.
    - Calculate conditional average demand per time_window + prod + weather/event.
    - Divide conditional averages by baseline averages with NULLIF(baseline, 0).
*/
CREATE TABLE IF NOT EXISTS EventWeatherInsight (
    time_window VARCHAR(15) NOT NULL,
    prod VARCHAR(30) NOT NULL,
    pct_dif_raining DECIMAL(6,4),
    pct_dif_not_raining DECIMAL(6,4),
    pct_dif_event_none DECIMAL(6,4),
    pct_dif_event_holiday DECIMAL(6,4),
    pct_dif_event_small DECIMAL(6,4),
    pct_dif_event_big DECIMAL(6,4),
    PRIMARY KEY (time_window, prod)
);

CREATE TABLE IF NOT EXISTS DayPrediction (
    week_day VARCHAR(10),
    time_window VARCHAR(15) NOT NULL,
    prod VARCHAR(30) NOT NULL,
    prediction DECIMAL(6,4),
    PRIMARY KEY (week_day,time_window, prod)
);

/*
    8. END-OF-DAY PERFORMANCE METRICS

    Captures daily KPIs before simulation state is cleared.

    End-of-day flush routine called at 00:00 simulated time:
        INSERT INTO ItemsInsight (date, prod, total_waiting_time, nr_trash_items)
        VALUES (CURRENT_DATE, ?, ?, ?);

    Annotations:
    - nr_trash_items counts items moved from SHELF -> TRASH because
      hora_atual >= HORA_PRAZO without an ORDERS_QUEUE match.
    - total_waiting_time is the sum of (HORA_RECEBIDO - HORA_EMISSAO), in minutes,
      for all orders processed through ORDERS_QUEUE -> ORDERS_ANSWERED.
    - Ideal total_waiting_time is 0.
    - These KPIs feed the end-of-day dashboard and can help tune MULTIPLICADOR_MANUAL.
*/
CREATE TABLE IF NOT EXISTS ItemsInsight (
    date DATE NOT NULL,
    prod VARCHAR(30) NOT NULL,
    total_waiting_time INT DEFAULT 0,
    nr_trash_items INT DEFAULT 0,
    PRIMARY KEY (date, prod)
);

/*
    PERFORMANCE INDEXES

    These indexes support the main access patterns:
    - Sales import analysis by date/hour/product.
    - Runtime and aggregation lookups by time_window/product.

    Note: ItemOrders is a view, so SQLite cannot create a normal index directly on it.
    Its performance is supported by idx_sales_date_hour_prod and Menu.product_id.
*/
CREATE INDEX IF NOT EXISTS idx_sales_date_hour_prod ON Sales(date, hour, product_id);
CREATE INDEX IF NOT EXISTS idx_ordersinsight_window_prod ON OrdersInsight(time_window, prod);
CREATE INDEX IF NOT EXISTS idx_eventweather_window_prod ON EventWeatherInsight(time_window, prod);

COMMIT;
